// 群
export const heroQun = [
  {
    'country': '5',
    'hero_type': 3,
    'icon_hero_id': 100008,
    'label': '群.张角.骑',
    'name': '张角',
    'pinyin': 'zhangjiao',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100008
  },
  {
    'country': '5',
    'hero_type': 3,
    'icon_hero_id': 100009,
    'label': '群.董卓.骑',
    'name': '董卓',
    'pinyin': 'dongzhuo',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100009
  },
  {
    'country': '5',
    'hero_type': 2,
    'icon_hero_id': 100011,
    'label': '群.贾诩.步',
    'name': '贾诩',
    'pinyin': 'jiaxu',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100011
  },
  {
    'country': '5',
    'hero_type': 1,
    'icon_hero_id': 100015,
    'label': '群.甄洛.弓',
    'name': '甄洛',
    'pinyin': 'zhenluo',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100015
  },
  {
    'country': '5',
    'hero_type': 3,
    'icon_hero_id': 100013,
    'label': '群.马超.骑',
    'name': '马超',
    'pinyin': 'machao',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100013
  },
  {
    'country': '5',
    'hero_type': 2,
    'icon_hero_id': 100337,
    'label': '群.貂蝉.步',
    'name': '貂蝉',
    'pinyin': 'diaochan',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100337
  },
  {
    'country': '5',
    'hero_type': 3,
    'icon_hero_id': 100046,
    'label': '群.董姬.骑',
    'name': '董姬',
    'pinyin': 'dongji',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100046
  },
  {
    'country': '5',
    'hero_type': 3,
    'icon_hero_id': 100047,
    'label': '群.严氏.骑',
    'name': '严氏',
    'pinyin': 'yanshi',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100047
  },
  {
    'country': '5',
    'hero_type': 2,
    'icon_hero_id': 100048,
    'label': '群.邹氏.步',
    'name': '邹氏',
    'pinyin': 'jushi',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100048
  },
  {
    'country': '5',
    'hero_type': 2,
    'icon_hero_id': 100049,
    'label': '群.华雄.步',
    'name': '华雄',
    'pinyin': 'huaxiong',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100049
  },
  {
    'country': '5',
    'hero_type': 3,
    'icon_hero_id': 100050,
    'label': '群.张辽.骑',
    'name': '张辽',
    'pinyin': 'zhangliao',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100050
  },
  {
    'country': '5',
    'hero_type': 3,
    'icon_hero_id': 100052,
    'label': '群.管亥.骑',
    'name': '管亥',
    'pinyin': 'guanhai',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100052
  },
  {
    'country': '5',
    'hero_type': 2,
    'icon_hero_id': 100053,
    'label': '群.徐荣.步',
    'name': '徐荣',
    'pinyin': 'xurong',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100053
  },
  {
    'country': '5',
    'hero_type': 3,
    'icon_hero_id': 100057,
    'label': '群.田丰.骑',
    'name': '田丰',
    'pinyin': 'tianfeng',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100057
  },
  {
    'country': '5',
    'hero_type': 3,
    'icon_hero_id': 100058,
    'label': '群.颜良.骑',
    'name': '颜良',
    'pinyin': 'yanliang',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100058
  },
  {
    'country': '5',
    'hero_type': 2,
    'icon_hero_id': 100059,
    'label': '群.文丑.步',
    'name': '文丑',
    'pinyin': 'wenchou',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100059
  },
  {
    'country': '5',
    'hero_type': 1,
    'icon_hero_id': 100110,
    'label': '群.李儒.弓',
    'name': '李儒',
    'pinyin': 'liru',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100110
  },
  {
    'country': '5',
    'hero_type': 3,
    'icon_hero_id': 100115,
    'label': '群.高顺.骑',
    'name': '高顺',
    'pinyin': 'gaoshun',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100115
  },
  {
    'country': '5',
    'hero_type': 2,
    'icon_hero_id': 100116,
    'label': '群.袁术.步',
    'name': '袁术',
    'pinyin': 'yuanshu',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100116
  },
  {
    'country': '5',
    'hero_type': 3,
    'icon_hero_id': 100131,
    'label': '群.赵云.骑',
    'name': '赵云',
    'pinyin': 'zhaoyun',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100131
  },
  {
    'country': '5',
    'hero_type': 3,
    'icon_hero_id': 100268,
    'label': '群.张绣.骑',
    'name': '张绣',
    'pinyin': 'zhangxiu',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100268
  },
  {
    'country': '5',
    'hero_type': 3,
    'icon_hero_id': 100062,
    'label': '群.马腾.骑',
    'name': '马腾',
    'pinyin': 'mateng',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100062
  },
  {
    'country': '5',
    'hero_type': 1,
    'icon_hero_id': 100351,
    'label': '群.张任.弓',
    'name': '张任',
    'pinyin': 'zhangren',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100351
  },
  {
    'country': '5',
    'hero_type': 3,
    'icon_hero_id': 100060,
    'label': '群.吕姬.骑',
    'name': '吕姬',
    'pinyin': 'lvji',
    'quality': 4,
    'season': 'S2',
    'star': 4,
    'value': 100060
  },
  {
    'country': '5',
    'hero_type': 2,
    'icon_hero_id': 100051,
    'label': '群.张梁.步',
    'name': '张梁',
    'pinyin': 'zhangliang',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100051
  },
  {
    'country': '5',
    'hero_type': 2,
    'icon_hero_id': 100123,
    'label': '群.张郃.步',
    'name': '张郃',
    'pinyin': 'zhangxia',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100123
  },
  {
    'country': '5',
    'hero_type': 3,
    'icon_hero_id': 100342,
    'label': '群.张横.骑',
    'name': '张横',
    'pinyin': 'zhangheng',
    'quality': 4,
    'season': 'S2',
    'star': 4,
    'value': 100342
  },
  {
    'country': '5',
    'hero_type': 3,
    'icon_hero_id': 100343,
    'label': '群.李堪.骑',
    'name': '李堪',
    'pinyin': 'likan',
    'quality': 4,
    'season': 'S2',
    'star': 4,
    'value': 100343
  },
  {
    'country': '5',
    'hero_type': 3,
    'icon_hero_id': 100344,
    'label': '群.马玩.骑',
    'name': '马玩',
    'pinyin': 'mawan',
    'quality': 4,
    'season': 'S2',
    'star': 4,
    'value': 100344
  },
  {
    'country': '5',
    'hero_type': 3,
    'icon_hero_id': 100345,
    'label': '群.杨秋.骑',
    'name': '杨秋',
    'pinyin': 'yangqiu',
    'quality': 4,
    'season': 'S2',
    'star': 4,
    'value': 100345
  },
  {
    'country': '5',
    'hero_type': 3,
    'icon_hero_id': 100346,
    'label': '群.侯选.骑',
    'name': '侯选',
    'pinyin': 'houxuan',
    'quality': 4,
    'season': 'S2',
    'star': 4,
    'value': 100346
  },
  {
    'country': '5',
    'hero_type': 3,
    'icon_hero_id': 100347,
    'label': '群.程银.骑',
    'name': '程银',
    'pinyin': 'chengyin',
    'quality': 4,
    'season': 'S2',
    'star': 4,
    'value': 100347
  },
  {
    'country': '5',
    'hero_type': 3,
    'icon_hero_id': 100348,
    'label': '群.成宜.骑',
    'name': '成宜',
    'pinyin': 'chengyi',
    'quality': 4,
    'season': 'S2',
    'star': 4,
    'value': 100348
  },
  {
    'country': '5',
    'hero_type': 1,
    'icon_hero_id': 100340,
    'label': '群.于吉.弓',
    'name': '于吉',
    'pinyin': 'yuji',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100340
  },
  {
    'country': '5',
    'hero_type': 1,
    'icon_hero_id': 100430,
    'label': '群.张宝.弓',
    'name': '张宝',
    'pinyin': 'zhangbao',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100430
  },
  {
    'country': '5',
    'hero_type': 3,
    'icon_hero_id': 100352,
    'label': '群.梁兴.骑',
    'name': '梁兴',
    'pinyin': 'liangxing',
    'quality': 4,
    'season': 'S2',
    'star': 4,
    'value': 100352
  },
  {
    'country': '5',
    'hero_type': 2,
    'icon_hero_id': 100372,
    'label': '群.妲己.步',
    'name': '妲己',
    'pinyin': 'daji',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100372
  },
  {
    'country': '5',
    'hero_type': 1,
    'icon_hero_id': 100377,
    'label': '群.骊姬.弓',
    'name': '骊姬',
    'pinyin': 'chiji',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100377
  },
  {
    'country': '5',
    'hero_type': 3,
    'icon_hero_id': 100376,
    'label': '群.褒姒.骑',
    'name': '褒姒',
    'pinyin': 'baosi',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100376
  },
  {
    'country': '5',
    'hero_type': 3,
    'icon_hero_id': 100374,
    'label': '群.妺喜.骑',
    'name': '妺喜',
    'pinyin': 'moxi',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100374
  },
  {
    'country': '5',
    'hero_type': 2,
    'icon_hero_id': 100474,
    'label': '群.张宁.步',
    'name': '张宁',
    'pinyin': 'zhangning',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100474
  },
  {
    'country': '5',
    'hero_type': 1,
    'icon_hero_id': 100479,
    'label': '群.吕布.弓',
    'name': '吕布',
    'pinyin': 'lvbu',
    'quality': 5,
    'season': 'S2',
    'star': 5,
    'value': 100479
  },
  {
    'country': '5',
    'hero_type': 3,
    'icon_hero_id': 100127,
    'label': '群.韩遂.骑',
    'name': '韩遂',
    'pinyin': 'hansui',
    'quality': 4,
    'season': 'S2',
    'star': 4,
    'value': 100482
  },
  {
    'country': '5',
    'hero_type': 2,
    'icon_hero_id': 100122,
    'label': '群.麴义.步',
    'name': '麴义',
    'pinyin': 'quyi',
    'quality': 4,
    'season': 'S2',
    'star': 4,
    'value': 100483
  },
  {
    'country': '5',
    'hero_type': 1,
    'icon_hero_id': 100487,
    'label': '群.张鲁.弓',
    'name': '张鲁',
    'pinyin': 'zhanglu',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100487
  },
  {
    'country': '5',
    'hero_type': 2,
    'icon_hero_id': 100488,
    'label': '群.孟获.步',
    'name': '孟获',
    'pinyin': 'menghuo',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100488
  },
  {
    'country': '5',
    'hero_type': 3,
    'icon_hero_id': 100489,
    'label': '群.孟优.骑',
    'name': '孟优',
    'pinyin': 'mengyou',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100489
  },
  {
    'country': '5',
    'hero_type': 1,
    'icon_hero_id': 100490,
    'label': '群.带来洞主.弓',
    'name': '带来洞主',
    'pinyin': 'dailaidongzhu',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100490
  },
  {
    'country': '5',
    'hero_type': 2,
    'icon_hero_id': 100491,
    'label': '群.金环三结.步',
    'name': '金环三结',
    'pinyin': 'jinhuansanjie',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100491
  },
  {
    'country': '5',
    'hero_type': 3,
    'icon_hero_id': 100494,
    'label': '群.祝融夫人.骑',
    'name': '祝融夫人',
    'pinyin': 'zhurongfuren',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100494
  },
  {
    'country': '5',
    'hero_type': 2,
    'icon_hero_id': 100519,
    'label': '群.兀突骨.步',
    'name': '兀突骨',
    'pinyin': 'wutugu',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100519
  },
  {
    'country': '5',
    'hero_type': 1,
    'icon_hero_id': 100520,
    'label': '群.花鬘.弓',
    'name': '花鬘',
    'pinyin': 'huaman',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100520
  },
  {
    'country': '5',
    'hero_type': 1,
    'icon_hero_id': 100015,
    'label': '群.甄洛.SP.弓',
    'name': '甄洛',
    'pinyin': 'zhenluo',
    'quality': 5,
    'season': 'SP',
    'star': 5,
    'value': 102005
  },
  {
    'country': '5',
    'hero_type': 2,
    'icon_hero_id': 100116,
    'label': '群.袁术.SP.步',
    'name': '袁术',
    'pinyin': 'yuanshu',
    'quality': 4,
    'season': 'SP',
    'star': 4,
    'value': 102010
  },
  {
    'country': '5',
    'hero_type': 3,
    'icon_hero_id': 100495,
    'label': '群.颜良＆文丑.骑',
    'name': '颜良＆文丑',
    'pinyin': 'yanliangwenchou',
    'quality': 5,
    'season': 'S3',
    'star': 5,
    'value': 100495
  },
  {
    'country': '5',
    'hero_type': 2,
    'icon_hero_id': 100097,
    'label': '群.蒯良＆蒯越.步',
    'name': '蒯良＆蒯越',
    'pinyin': 'kuailiangkuaiyue',
    'quality': 4,
    'season': 'S3',
    'star': 4,
    'value': 100499
  },
  {
    'country': '5',
    'hero_type': 2,
    'icon_hero_id': 100186,
    'label': '群.审配.步',
    'name': '审配',
    'pinyin': 'shenpei',
    'quality': 4,
    'season': 'S3',
    'star': 4,
    'value': 100500
  },
  {
    'country': '5',
    'hero_type': 3,
    'icon_hero_id': 100506,
    'label': '群.刘豹.骑',
    'name': '刘豹',
    'pinyin': 'liubao',
    'quality': 4,
    'season': 'S3',
    'star': 4,
    'value': 100506
  },
  {
    'country': '5',
    'hero_type': 3,
    'icon_hero_id': 100507,
    'label': '群.楼班.骑',
    'name': '楼班',
    'pinyin': 'louban',
    'quality': 4,
    'season': 'S3',
    'star': 4,
    'value': 100507
  },
  {
    'country': '5',
    'hero_type': 2,
    'icon_hero_id': 100508,
    'label': '群.严白虎.步',
    'name': '严白虎',
    'pinyin': 'yanbaihu',
    'quality': 4,
    'season': 'S3',
    'star': 4,
    'value': 100508
  },
  {
    'country': '5',
    'hero_type': 3,
    'icon_hero_id': 100452,
    'label': '群.木鹿大王.骑',
    'name': '木鹿大王',
    'pinyin': 'muludaiwang',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100452
  },
  {
    'country': '5',
    'hero_type': 3,
    'icon_hero_id': 100529,
    'label': '群.步度根.骑',
    'name': '步度根',
    'pinyin': 'buduogen',
    'quality': 4,
    'season': 'XP',
    'star': 4,
    'value': 100529
  },
  {
    'country': '5',
    'hero_type': 3,
    'icon_hero_id': 100008,
    'label': '群.张角.SP.骑',
    'name': '张角',
    'pinyin': 'zhangjiao',
    'quality': 5,
    'season': 'SP',
    'star': 5,
    'value': 102014
  },
  {
    'country': '5',
    'hero_type': 1,
    'icon_hero_id': 100443,
    'label': '群.陈宫.弓',
    'name': '陈宫',
    'pinyin': 'chengong',
    'quality': 5,
    'season': 'XP',
    'star': 5,
    'value': 100443
  },
  {
    'country': '5',
    'hero_type': 3,
    'icon_hero_id': 100550,
    'label': '群.轲比能.骑',
    'name': '轲比能',
    'pinyin': 'kebineng',
    'quality': 5,
    'season': 'XP',
    'star': 5,
    'value': 100550
  },
  {
    'country': '5',
    'hero_type': 2,
    'icon_hero_id': 100557,
    'label': '群.张梁.SP.步',
    'name': '张梁',
    'pinyin': 'zhangliang',
    'quality': 5,
    'season': 'SP',
    'star': 5,
    'value': 100557
  },
  {
    'country': '5',
    'hero_type': 1,
    'icon_hero_id': 100562,
    'label': '群.张宝.SP.弓',
    'name': '张宝',
    'pinyin': 'zhangbao',
    'quality': 5,
    'season': 'SP',
    'star': 5,
    'value': 100562
  },
  {
    'country': '5',
    'hero_type': 3,
    'icon_hero_id': 100586,
    'label': '群.庞德.骑',
    'name': '庞德',
    'pinyin': 'pangde',
    'quality': 5,
    'season': 'XP',
    'star': 5,
    'value': 100586
  },
  {
    'country': '5',
    'hero_type': 1,
    'icon_hero_id': 100592,
    'label': '群.董白.弓',
    'name': '董白',
    'pinyin': 'dongbai',
    'quality': 5,
    'season': 'XP',
    'star': 5,
    'value': 100592
  },
  {
    'country': '5',
    'hero_type': 3,
    'icon_hero_id': 100593,
    'label': '群.张郃.骑',
    'name': '张郃',
    'pinyin': 'zhangxia',
    'quality': 5,
    'season': 'XP',
    'star': 5,
    'value': 100593
  },
  {
    'country': '5',
    'hero_type': 1,
    'icon_hero_id': 100604,
    'label': '群.李儒.弓',
    'name': '李儒',
    'pinyin': 'liru',
    'quality': 5,
    'season': 'XP',
    'star': 5,
    'value': 100604
  },
  {
    'country': '5',
    'hero_type': 3,
    'icon_hero_id': 100620,
    'label': '群.张绣.骑',
    'name': '张绣',
    'pinyin': 'zhangxiu',
    'quality': 5,
    'season': 'XP',
    'star': 5,
    'value': 100620
  },
  {
    'country': '5',
    'hero_type': 2,
    'icon_hero_id': 100634,
    'label': '群.吕姬.步',
    'name': '吕姬',
    'pinyin': 'lvji',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100634
  },
  {
    'country': '5',
    'hero_type': 3,
    'icon_hero_id': 100635,
    'label': '群.丘力居.骑',
    'name': '丘力居',
    'pinyin': 'qiuliju',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100635
  },
  {
    'country': '5',
    'hero_type': 2,
    'icon_hero_id': 100636,
    'label': '群.迷当大王.步',
    'name': '迷当大王',
    'pinyin': 'midangdawang',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100636
  },
  {
    'country': '5',
    'hero_type': 3,
    'icon_hero_id': 100637,
    'label': '群.俄何烧戈.骑',
    'name': '俄何烧戈',
    'pinyin': 'eheshaoge',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100637
  },
  {
    'country': '5',
    'hero_type': 3,
    'icon_hero_id': 100638,
    'label': '群.越吉.骑',
    'name': '越吉',
    'pinyin': 'yueji',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100638
  },
  {
    'country': '5',
    'hero_type': 2,
    'icon_hero_id': 100639,
    'label': '群.彻里吉.步',
    'name': '彻里吉',
    'pinyin': 'cheliji',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100639
  },
  {
    'country': '5',
    'hero_type': 1,
    'icon_hero_id': 100640,
    'label': '群.朵思大王.弓',
    'name': '朵思大王',
    'pinyin': 'duosidaiwang',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100640
  },
  {
    'country': '5',
    'hero_type': 1,
    'icon_hero_id': 100646,
    'label': '群.于吉.弓',
    'name': '于吉',
    'pinyin': 'yuji',
    'quality': 5,
    'season': 'XP',
    'star': 5,
    'value': 100646
  },
  {
    'country': '5',
    'hero_type': 3,
    'icon_hero_id': 100647,
    'label': '群.华雄.骑',
    'name': '华雄',
    'pinyin': 'huaxiong',
    'quality': 5,
    'season': 'XP',
    'star': 5,
    'value': 100647
  },
  {
    'country': '5',
    'hero_type': 3,
    'icon_hero_id': 100656,
    'label': '群.高顺.骑',
    'name': '高顺',
    'pinyin': 'gaoshun',
    'quality': 5,
    'season': 'XP',
    'star': 5,
    'value': 100656
  },
  {
    'country': '5',
    'hero_type': 3,
    'icon_hero_id': 100265,
    'label': '群.侯成.骑',
    'name': '侯成',
    'pinyin': 'houcheng',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100664
  },
  {
    'country': '5',
    'hero_type': 1,
    'icon_hero_id': 100269,
    'label': '群.魏续.弓',
    'name': '魏续',
    'pinyin': 'weixu',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100665
  },
  {
    'country': '5',
    'hero_type': 3,
    'icon_hero_id': 100338,
    'label': '群.宋宪.骑',
    'name': '宋宪',
    'pinyin': 'songxian',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100666
  },
  {
    'country': '5',
    'hero_type': 1,
    'icon_hero_id': 100113,
    'label': '群.李肃.弓',
    'name': '李肃',
    'pinyin': 'lisu',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100667
  },
  {
    'country': '5',
    'hero_type': 3,
    'icon_hero_id': 100184,
    'label': '群.李傕＆郭汜.骑',
    'name': '李傕＆郭汜',
    'pinyin': 'liqueguosi',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100668
  },
  {
    'country': '5',
    'hero_type': 1,
    'icon_hero_id': 100670,
    'label': '群.袁绍.弓',
    'name': '袁绍',
    'pinyin': 'yuanshao',
    'quality': 5,
    'season': 'XP',
    'star': 5,
    'value': 100670
  },
  {
    'country': '5',
    'hero_type': 3,
    'icon_hero_id': 100677,
    'label': '群.公孙瓒.骑',
    'name': '公孙瓒',
    'pinyin': 'gongsunzan',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100677
  },
  {
    'country': '5',
    'hero_type': 1,
    'icon_hero_id': 100690,
    'label': '群.西施.弓',
    'name': '西施',
    'pinyin': 'xishi',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100690
  },
  {
    'country': '5',
    'hero_type': 3,
    'icon_hero_id': 100692,
    'label': '群.田丰.骑',
    'name': '田丰',
    'pinyin': 'tianfeng',
    'quality': 5,
    'season': 'XP',
    'star': 5,
    'value': 100692
  },
  {
    'country': '5',
    'hero_type': 2,
    'icon_hero_id': 100771,
    'label': '群.沮授.步',
    'name': '沮授',
    'pinyin': 'jushou',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100771
  },
  {
    'country': '5',
    'hero_type': 3,
    'icon_hero_id': 100772,
    'label': '群.许攸.骑',
    'name': '许攸',
    'pinyin': 'xuyou',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100772
  },
  {
    'country': '5',
    'hero_type': 1,
    'icon_hero_id': 110311,
    'label': '群.侍卫.弓',
    'name': '侍卫',
    'pinyin': 'shiwei',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 110351
  },
  {
    'country': '5',
    'hero_type': 2,
    'icon_hero_id': 110311,
    'label': '群.侍卫.步',
    'name': '侍卫',
    'pinyin': 'shiwei',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 110352
  },
  {
    'country': '5',
    'hero_type': 3,
    'icon_hero_id': 110311,
    'label': '群.侍卫.骑',
    'name': '侍卫',
    'pinyin': 'shiwei',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 110353
  },
  {
    'country': '5',
    'hero_type': 1,
    'icon_hero_id': 110411,
    'label': '群.侍卫.弓',
    'name': '侍卫',
    'pinyin': 'shiwei',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 110451
  },
  {
    'country': '5',
    'hero_type': 2,
    'icon_hero_id': 110411,
    'label': '群.侍卫.步',
    'name': '侍卫',
    'pinyin': 'shiwei',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 110452
  },
  {
    'country': '5',
    'hero_type': 3,
    'icon_hero_id': 110411,
    'label': '群.侍卫.骑',
    'name': '侍卫',
    'pinyin': 'shiwei',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 110453
  }]
// 吴
export const heroWu = [
  {
    'country': '4',
    'hero_type': 1,
    'icon_hero_id': 100030,
    'label': '吴.孙权.弓',
    'name': '孙权',
    'pinyin': 'sunquan',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100030
  },
  {
    'country': '4',
    'hero_type': 1,
    'icon_hero_id': 100031,
    'label': '吴.周瑜.弓',
    'name': '周瑜',
    'pinyin': 'zhouyu',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100031
  },
  {
    'country': '4',
    'hero_type': 1,
    'icon_hero_id': 100032,
    'label': '吴.周姬.弓',
    'name': '周姬',
    'pinyin': 'zhouji',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100032
  },
  {
    'country': '4',
    'hero_type': 2,
    'icon_hero_id': 100033,
    'label': '吴.孙坚.步',
    'name': '孙坚',
    'pinyin': 'sunjian',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100033
  },
  {
    'country': '4',
    'hero_type': 1,
    'icon_hero_id': 100036,
    'label': '吴.孙尚香.弓',
    'name': '孙尚香',
    'pinyin': 'sunshangxiang',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100036
  },
  {
    'country': '4',
    'hero_type': 2,
    'icon_hero_id': 100034,
    'label': '吴.甘宁.步',
    'name': '甘宁',
    'pinyin': 'ganning',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100034
  },
  {
    'country': '4',
    'hero_type': 1,
    'icon_hero_id': 100035,
    'label': '吴.吕蒙.弓',
    'name': '吕蒙',
    'pinyin': 'lvmeng',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100035
  },
  {
    'country': '4',
    'hero_type': 2,
    'icon_hero_id': 100086,
    'label': '吴.周泰.步',
    'name': '周泰',
    'pinyin': 'zhoutai',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100086
  },
  {
    'country': '4',
    'hero_type': 1,
    'icon_hero_id': 100087,
    'label': '吴.徐盛.弓',
    'name': '徐盛',
    'pinyin': 'xucheng',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100087
  },
  {
    'country': '4',
    'hero_type': 3,
    'icon_hero_id': 100088,
    'label': '吴.孙坚.骑',
    'name': '孙坚',
    'pinyin': 'sunjian',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100088
  },
  {
    'country': '4',
    'hero_type': 3,
    'icon_hero_id': 100089,
    'label': '吴.孙策.骑',
    'name': '孙策',
    'pinyin': 'sunce',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100089
  },
  {
    'country': '4',
    'hero_type': 1,
    'icon_hero_id': 100090,
    'label': '吴.太史慈.弓',
    'name': '太史慈',
    'pinyin': 'taishici',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100090
  },
  {
    'country': '4',
    'hero_type': 3,
    'icon_hero_id': 100091,
    'label': '吴.吴夫人.骑',
    'name': '吴夫人',
    'pinyin': 'wufuren',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100091
  },
  {
    'country': '4',
    'hero_type': 1,
    'icon_hero_id': 100094,
    'label': '吴.小乔.弓',
    'name': '小乔',
    'pinyin': 'xiaoqiao',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100094
  },
  {
    'country': '4',
    'hero_type': 1,
    'icon_hero_id': 100095,
    'label': '吴.大乔.弓',
    'name': '大乔',
    'pinyin': 'daqiao',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100095
  },
  {
    'country': '4',
    'hero_type': 1,
    'icon_hero_id': 100157,
    'label': '吴.甘宁.弓',
    'name': '甘宁',
    'pinyin': 'ganning',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100157
  },
  {
    'country': '4',
    'hero_type': 3,
    'icon_hero_id': 100162,
    'label': '吴.程普.骑',
    'name': '程普',
    'pinyin': 'chengpu',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100162
  },
  {
    'country': '4',
    'hero_type': 1,
    'icon_hero_id': 100163,
    'label': '吴.鲁肃.弓',
    'name': '鲁肃',
    'pinyin': 'lusu',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100163
  },
  {
    'country': '4',
    'hero_type': 1,
    'icon_hero_id': 100426,
    'label': '吴.凌统.弓',
    'name': '凌统',
    'pinyin': 'lingtong',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100426
  },
  {
    'country': '4',
    'hero_type': 2,
    'icon_hero_id': 100439,
    'label': '吴.黄盖.步',
    'name': '黄盖',
    'pinyin': 'huanggai',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100439
  },
  {
    'country': '4',
    'hero_type': 2,
    'icon_hero_id': 100092,
    'label': '吴.陆逊.步',
    'name': '陆逊',
    'pinyin': 'luxun',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100092
  },
  {
    'country': '4',
    'hero_type': 1,
    'icon_hero_id': 100093,
    'label': '吴.徐夫人.弓',
    'name': '徐夫人',
    'pinyin': 'xufuren',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100093
  },
  {
    'country': '4',
    'hero_type': 1,
    'icon_hero_id': 100156,
    'label': '吴.韩当.弓',
    'name': '韩当',
    'pinyin': 'handang',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100156
  },
  {
    'country': '4',
    'hero_type': 1,
    'icon_hero_id': 100159,
    'label': '吴.蒋钦.弓',
    'name': '蒋钦',
    'pinyin': 'jiangqin',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100159
  },
  {
    'country': '4',
    'hero_type': 2,
    'icon_hero_id': 100221,
    'label': '吴.朱桓.步',
    'name': '朱桓',
    'pinyin': 'zhuhuan',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100221
  },
  {
    'country': '4',
    'hero_type': 1,
    'icon_hero_id': 100243,
    'label': '吴.孙桓.弓',
    'name': '孙桓',
    'pinyin': 'sunhuan',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100243
  },
  {
    'country': '4',
    'hero_type': 2,
    'icon_hero_id': 100245,
    'label': '吴.董袭.步',
    'name': '董袭',
    'pinyin': 'dongxi',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100245
  },
  {
    'country': '4',
    'hero_type': 2,
    'icon_hero_id': 100424,
    'label': '吴.小乔＆大乔.步',
    'name': '小乔＆大乔',
    'pinyin': 'xiaoqiaodaqiao',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100424
  },
  {
    'country': '4',
    'hero_type': 2,
    'icon_hero_id': 100478,
    'label': '吴.陆逊.步',
    'name': '陆逊',
    'pinyin': 'luxun',
    'quality': 5,
    'season': 'S2',
    'star': 5,
    'value': 100478
  },
  {
    'country': '4',
    'hero_type': 3,
    'icon_hero_id': 100481,
    'label': '吴.丁奉.骑',
    'name': '丁奉',
    'pinyin': 'dingfeng',
    'quality': 4,
    'season': 'S2',
    'star': 4,
    'value': 100481
  },
  {
    'country': '4',
    'hero_type': 1,
    'icon_hero_id': 100522,
    'label': '吴.诸葛恪.弓',
    'name': '诸葛恪',
    'pinyin': 'zhugeke',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100522
  },
  {
    'country': '4',
    'hero_type': 2,
    'icon_hero_id': 100523,
    'label': '吴.全琮.步',
    'name': '全琮',
    'pinyin': 'quancong',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100523
  },
  {
    'country': '4',
    'hero_type': 2,
    'icon_hero_id': 100589,
    'label': '吴.周泰.步',
    'name': '周泰',
    'pinyin': 'zhoutai',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100589
  },
  {
    'country': '4',
    'hero_type': 1,
    'icon_hero_id': 100090,
    'label': '吴.太史慈.SP.弓',
    'name': '太史慈',
    'pinyin': 'taishici',
    'quality': 5,
    'season': 'SP',
    'star': 5,
    'value': 102003
  },
  {
    'country': '4',
    'hero_type': 3,
    'icon_hero_id': 100091,
    'label': '吴.吴夫人.SP.骑',
    'name': '吴夫人',
    'pinyin': 'wufuren',
    'quality': 4,
    'season': 'SP',
    'star': 4,
    'value': 102008
  },
  {
    'country': '4',
    'hero_type': 2,
    'icon_hero_id': 100497,
    'label': '吴.步皇后.步',
    'name': '步皇后',
    'pinyin': 'buhuanghou',
    'quality': 5,
    'season': 'S3',
    'star': 5,
    'value': 100497
  },
  {
    'country': '4',
    'hero_type': 2,
    'icon_hero_id': 100246,
    'label': '吴.潘璋.步',
    'name': '潘璋',
    'pinyin': 'panzhang',
    'quality': 4,
    'season': 'S3',
    'star': 4,
    'value': 100504
  },
  {
    'country': '4',
    'hero_type': 1,
    'icon_hero_id': 100161,
    'label': '吴.张昭.弓',
    'name': '张昭',
    'pinyin': 'zhangzhao',
    'quality': 4,
    'season': 'S3',
    'star': 4,
    'value': 100505
  },
  {
    'country': '4',
    'hero_type': 3,
    'icon_hero_id': 100450,
    'label': '吴.孙策.骑',
    'name': '孙策',
    'pinyin': 'sunce',
    'quality': 5,
    'season': 'XP',
    'star': 5,
    'value': 100450
  },
  {
    'country': '4',
    'hero_type': 1,
    'icon_hero_id': 100164,
    'label': '吴.诸葛瑾.弓',
    'name': '诸葛瑾',
    'pinyin': 'zhugejin',
    'quality': 4,
    'season': 'XP',
    'star': 4,
    'value': 100527
  },
  {
    'country': '4',
    'hero_type': 2,
    'icon_hero_id': 100528,
    'label': '吴.吾粲.步',
    'name': '吾粲',
    'pinyin': 'wucan',
    'quality': 4,
    'season': 'XP',
    'star': 4,
    'value': 100528
  },
  {
    'country': '4',
    'hero_type': 2,
    'icon_hero_id': 100032,
    'label': '吴.周姬.SP.步',
    'name': '周姬',
    'pinyin': 'zhouji',
    'quality': 5,
    'season': 'SP',
    'star': 5,
    'value': 102017
  },
  {
    'country': '4',
    'hero_type': 2,
    'icon_hero_id': 100574,
    'label': '吴.陆抗.步',
    'name': '陆抗',
    'pinyin': 'lukang',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100574
  },
  {
    'country': '4',
    'hero_type': 1,
    'icon_hero_id': 100616,
    'label': '吴.凌统.弓',
    'name': '凌统',
    'pinyin': 'lingtong',
    'quality': 5,
    'season': 'XP',
    'star': 5,
    'value': 100616
  },
  {
    'country': '4',
    'hero_type': 2,
    'icon_hero_id': 100619,
    'label': '吴.大乔.步',
    'name': '大乔',
    'pinyin': 'daqiao',
    'quality': 5,
    'season': 'XP',
    'star': 5,
    'value': 100619
  },
  {
    'country': '4',
    'hero_type': 2,
    'icon_hero_id': 100641,
    'label': '吴.朱然.步',
    'name': '朱然',
    'pinyin': 'zhuran',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100641
  },
  {
    'country': '4',
    'hero_type': 1,
    'icon_hero_id': 100648,
    'label': '吴.张昭.弓',
    'name': '张昭',
    'pinyin': 'zhangzhao',
    'quality': 5,
    'season': 'XP',
    'star': 5,
    'value': 100648
  },
  {
    'country': '4',
    'hero_type': 1,
    'icon_hero_id': 100654,
    'label': '吴.孙鲁班.弓',
    'name': '孙鲁班',
    'pinyin': 'sunluban',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100654
  },
  {
    'country': '4',
    'hero_type': 1,
    'icon_hero_id': 100671,
    'label': '吴.蒋钦.弓',
    'name': '蒋钦',
    'pinyin': 'jiangqin',
    'quality': 5,
    'season': 'XP',
    'star': 5,
    'value': 100671
  },
  {
    'country': '4',
    'hero_type': 2,
    'icon_hero_id': 100684,
    'label': '吴.程普.步',
    'name': '程普',
    'pinyin': 'chengpu',
    'quality': 5,
    'season': 'XP',
    'star': 5,
    'value': 100684
  },
  {
    'country': '4',
    'hero_type': 1,
    'icon_hero_id': 100687,
    'label': '吴.小乔.弓',
    'name': '小乔',
    'pinyin': 'xiaoqiao',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100687
  },
  {
    'country': '4',
    'hero_type': 1,
    'icon_hero_id': 100700,
    'label': '吴.朱治.弓',
    'name': '朱治',
    'pinyin': 'zhuzhi',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100700
  },
  {
    'country': '4',
    'hero_type': 2,
    'icon_hero_id': 100741,
    'label': '吴.鲁肃.步',
    'name': '鲁肃',
    'pinyin': 'lusu',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100741
  },
  {
    'country': '4',
    'hero_type': 2,
    'icon_hero_id': 100783,
    'label': '吴.黄盖.步',
    'name': '黄盖',
    'pinyin': 'huanggai',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100783
  },
  {
    'country': '4',
    'hero_type': 2,
    'icon_hero_id': 100784,
    'label': '吴.周瑜.步',
    'name': '周瑜',
    'pinyin': 'zhouyu',
    'quality': 5,
    'season': 'XP',
    'star': 5,
    'value': 100784
  },
  {
    'country': '4',
    'hero_type': 1,
    'icon_hero_id': 110311,
    'label': '吴.侍卫.弓',
    'name': '侍卫',
    'pinyin': 'shiwei',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 110341
  },
  {
    'country': '4',
    'hero_type': 2,
    'icon_hero_id': 110311,
    'label': '吴.侍卫.步',
    'name': '侍卫',
    'pinyin': 'shiwei',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 110342
  },
  {
    'country': '4',
    'hero_type': 3,
    'icon_hero_id': 110311,
    'label': '吴.侍卫.骑',
    'name': '侍卫',
    'pinyin': 'shiwei',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 110343
  },
  {
    'country': '4',
    'hero_type': 1,
    'icon_hero_id': 110411,
    'label': '吴.侍卫.弓',
    'name': '侍卫',
    'pinyin': 'shiwei',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 110441
  },
  {
    'country': '4',
    'hero_type': 2,
    'icon_hero_id': 110411,
    'label': '吴.侍卫.步',
    'name': '侍卫',
    'pinyin': 'shiwei',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 110442
  },
  {
    'country': '4',
    'hero_type': 3,
    'icon_hero_id': 110411,
    'label': '吴.侍卫.骑',
    'name': '侍卫',
    'pinyin': 'shiwei',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 110443
  }
]
// 蜀
export const heroShu = [
  {
    'country': '3',
    'hero_type': 2,
    'icon_hero_id': 100016,
    'label': '蜀.刘备.步',
    'name': '刘备',
    'pinyin': 'liubei',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100016
  },
  {
    'country': '3',
    'hero_type': 2,
    'icon_hero_id': 100017,
    'label': '蜀.诸葛亮.步',
    'name': '诸葛亮',
    'pinyin': 'zhugeliang',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100017
  },
  {
    'country': '3',
    'hero_type': 3,
    'icon_hero_id': 100019,
    'label': '蜀.马云禄.骑',
    'name': '马云禄',
    'pinyin': 'mayunlu',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100019
  },
  {
    'country': '3',
    'hero_type': 2,
    'icon_hero_id': 100020,
    'label': '蜀.黄月英.步',
    'name': '黄月英',
    'pinyin': 'huangyueying',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100020
  },
  {
    'country': '3',
    'hero_type': 2,
    'icon_hero_id': 100074,
    'label': '蜀.姜维.步',
    'name': '姜维',
    'pinyin': 'jiangwei',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100074
  },
  {
    'country': '3',
    'hero_type': 2,
    'icon_hero_id': 100021,
    'label': '蜀.赵云.步',
    'name': '赵云',
    'pinyin': 'zhaoyun',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100021
  },
  {
    'country': '3',
    'hero_type': 3,
    'icon_hero_id': 100022,
    'label': '蜀.张飞.骑',
    'name': '张飞',
    'pinyin': 'zhangfei',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100022
  },
  {
    'country': '3',
    'hero_type': 2,
    'icon_hero_id': 100063,
    'label': '蜀.甘皇后.步',
    'name': '甘皇后',
    'pinyin': 'ganhuanghou',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100063
  },
  {
    'country': '3',
    'hero_type': 1,
    'icon_hero_id': 100064,
    'label': '蜀.麋夫人.弓',
    'name': '麋夫人',
    'pinyin': 'mifuren',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100064
  },
  {
    'country': '3',
    'hero_type': 2,
    'icon_hero_id': 100065,
    'label': '蜀.关羽.步',
    'name': '关羽',
    'pinyin': 'guanyu',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100065
  },
  {
    'country': '3',
    'hero_type': 2,
    'icon_hero_id': 100066,
    'label': '蜀.魏延.步',
    'name': '魏延',
    'pinyin': 'weiyan',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100066
  },
  {
    'country': '3',
    'hero_type': 3,
    'icon_hero_id': 100067,
    'label': '蜀.徐庶.骑',
    'name': '徐庶',
    'pinyin': 'xushu',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100067
  },
  {
    'country': '3',
    'hero_type': 2,
    'icon_hero_id': 100068,
    'label': '蜀.张飞.步',
    'name': '张飞',
    'pinyin': 'zhangfei',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100068
  },
  {
    'country': '3',
    'hero_type': 2,
    'icon_hero_id': 100069,
    'label': '蜀.庞统.步',
    'name': '庞统',
    'pinyin': 'pangtong',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100069
  },
  {
    'country': '3',
    'hero_type': 3,
    'icon_hero_id': 100070,
    'label': '蜀.穆皇后.骑',
    'name': '穆皇后',
    'pinyin': 'muhuanghou',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100070
  },
  {
    'country': '3',
    'hero_type': 2,
    'icon_hero_id': 100072,
    'label': '蜀.关银屏.步',
    'name': '关银屏',
    'pinyin': 'guanyinping',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100072
  },
  {
    'country': '3',
    'hero_type': 1,
    'icon_hero_id': 100129,
    'label': '蜀.关平.弓',
    'name': '关平',
    'pinyin': 'guanping',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100129
  },
  {
    'country': '3',
    'hero_type': 3,
    'icon_hero_id': 100140,
    'label': '蜀.马超.骑',
    'name': '马超',
    'pinyin': 'machao',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100140
  },
  {
    'country': '3',
    'hero_type': 2,
    'icon_hero_id': 100329,
    'label': '蜀.敬哀皇后.步',
    'name': '敬哀皇后',
    'pinyin': 'jingaihuanghou',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100329
  },
  {
    'country': '3',
    'hero_type': 2,
    'icon_hero_id': 100398,
    'label': '蜀.关兴＆张苞.步',
    'name': '关兴＆张苞',
    'pinyin': 'guanxingzhangbao',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100398
  },
  {
    'country': '3',
    'hero_type': 3,
    'icon_hero_id': 100071,
    'label': '蜀.马姬.骑',
    'name': '马姬',
    'pinyin': 'maji',
    'quality': 4,
    'season': 'S2',
    'star': 4,
    'value': 100071
  },
  {
    'country': '3',
    'hero_type': 1,
    'icon_hero_id': 100134,
    'label': '蜀.严颜.弓',
    'name': '严颜',
    'pinyin': 'yanyan',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100134
  },
  {
    'country': '3',
    'hero_type': 3,
    'icon_hero_id': 100139,
    'label': '蜀.马岱.骑',
    'name': '马岱',
    'pinyin': 'madai',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100139
  },
  {
    'country': '3',
    'hero_type': 2,
    'icon_hero_id': 100331,
    'label': '蜀.霍弋.步',
    'name': '霍弋',
    'pinyin': 'huoyi',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100331
  },
  {
    'country': '3',
    'hero_type': 2,
    'icon_hero_id': 100334,
    'label': '蜀.黄权.步',
    'name': '黄权',
    'pinyin': 'huangquan',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100334
  },
  {
    'country': '3',
    'hero_type': 2,
    'icon_hero_id': 100442,
    'label': '蜀.黄忠.步',
    'name': '黄忠',
    'pinyin': 'huangzhong',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100442
  },
  {
    'country': '3',
    'hero_type': 1,
    'icon_hero_id': 100358,
    'label': '蜀.张姬.弓',
    'name': '张姬',
    'pinyin': 'zhangji',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100358
  },
  {
    'country': '3',
    'hero_type': 2,
    'icon_hero_id': 100477,
    'label': '蜀.庞统.步',
    'name': '庞统',
    'pinyin': 'pangtong',
    'quality': 5,
    'season': 'S2',
    'star': 5,
    'value': 100477
  },
  {
    'country': '3',
    'hero_type': 3,
    'icon_hero_id': 100326,
    'label': '蜀.夏侯月姬.骑',
    'name': '夏侯月姬',
    'pinyin': 'xiahouyueji',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100326
  },
  {
    'country': '3',
    'hero_type': 1,
    'icon_hero_id': 100524,
    'label': '蜀.沙摩柯.弓',
    'name': '沙摩柯',
    'pinyin': 'shamoke',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100524
  },
  {
    'country': '3',
    'hero_type': 3,
    'icon_hero_id': 100525,
    'label': '蜀.赵统＆赵广.骑',
    'name': '赵统＆赵广',
    'pinyin': 'zhaotongzhaoguang',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100525
  },
  {
    'country': '3',
    'hero_type': 3,
    'icon_hero_id': 100534,
    'label': '蜀.徐庶.SP.骑',
    'name': '徐庶',
    'pinyin': 'xushu',
    'quality': 5,
    'season': 'SP',
    'star': 5,
    'value': 100534
  },
  {
    'country': '3',
    'hero_type': 3,
    'icon_hero_id': 100582,
    'label': '蜀.法正.骑',
    'name': '法正',
    'pinyin': 'fazheng',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100582
  },
  {
    'country': '3',
    'hero_type': 2,
    'icon_hero_id': 100021,
    'label': '蜀.赵云.SP.步',
    'name': '赵云',
    'pinyin': 'zhaoyun',
    'quality': 5,
    'season': 'SP',
    'star': 5,
    'value': 102001
  },
  {
    'country': '3',
    'hero_type': 1,
    'icon_hero_id': 100129,
    'label': '蜀.关平.SP.弓',
    'name': '关平',
    'pinyin': 'guanping',
    'quality': 4,
    'season': 'SP',
    'star': 4,
    'value': 102006
  },
  {
    'country': '3',
    'hero_type': 1,
    'icon_hero_id': 100496,
    'label': '蜀.诸葛亮.弓',
    'name': '诸葛亮',
    'pinyin': 'zhugeliang',
    'quality': 5,
    'season': 'S3',
    'star': 5,
    'value': 100496
  },
  {
    'country': '3',
    'hero_type': 2,
    'icon_hero_id': 100133,
    'label': '蜀.陈到.步',
    'name': '陈到',
    'pinyin': 'chendao',
    'quality': 4,
    'season': 'S3',
    'star': 4,
    'value': 100501
  },
  {
    'country': '3',
    'hero_type': 1,
    'icon_hero_id': 100074,
    'label': '蜀.姜维.SP.弓',
    'name': '姜维',
    'pinyin': 'jiangwei',
    'quality': 5,
    'season': 'SP',
    'star': 5,
    'value': 102012
  },
  {
    'country': '3',
    'hero_type': 3,
    'icon_hero_id': 100451,
    'label': '蜀.关羽.骑',
    'name': '关羽',
    'pinyin': 'guanyu',
    'quality': 5,
    'season': 'XP',
    'star': 5,
    'value': 100451
  },
  {
    'country': '3',
    'hero_type': 2,
    'icon_hero_id': 100532,
    'label': '蜀.蜀三相.步',
    'name': '蜀三相',
    'pinyin': 'shusanxiang',
    'quality': 4,
    'season': 'XP',
    'star': 4,
    'value': 100532
  },
  {
    'country': '3',
    'hero_type': 1,
    'icon_hero_id': 100036,
    'label': '蜀.孙尚香.SP.弓',
    'name': '孙尚香',
    'pinyin': 'sunshangxiang',
    'quality': 5,
    'season': 'SP',
    'star': 5,
    'value': 102015
  },
  {
    'country': '3',
    'hero_type': 3,
    'icon_hero_id': 100494,
    'label': '蜀.祝融夫人.SP.骑',
    'name': '祝融夫人',
    'pinyin': 'zhurongfuren',
    'quality': 5,
    'season': 'SP',
    'star': 5,
    'value': 102016
  },
  {
    'country': '3',
    'hero_type': 3,
    'icon_hero_id': 100615,
    'label': '蜀.马岱.骑',
    'name': '马岱',
    'pinyin': 'madai',
    'quality': 5,
    'season': 'XP',
    'star': 5,
    'value': 100615
  },
  {
    'country': '3',
    'hero_type': 3,
    'icon_hero_id': 100631,
    'label': '蜀.严颜.骑',
    'name': '严颜',
    'pinyin': 'yanyan',
    'quality': 5,
    'season': 'XP',
    'star': 5,
    'value': 100631
  },
  {
    'country': '3',
    'hero_type': 3,
    'icon_hero_id': 100642,
    'label': '蜀.关索.骑',
    'name': '关索',
    'pinyin': 'guansuo',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100642
  },
  {
    'country': '3',
    'hero_type': 2,
    'icon_hero_id': 100649,
    'label': '蜀.魏延.步',
    'name': '魏延',
    'pinyin': 'weiyan',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100649
  },
  {
    'country': '3',
    'hero_type': 2,
    'icon_hero_id': 100653,
    'label': '蜀.关兴＆张苞.步',
    'name': '关兴＆张苞',
    'pinyin': 'guanxingzhangbao',
    'quality': 5,
    'season': 'XP',
    'star': 5,
    'value': 100653
  },
  {
    'country': '3',
    'hero_type': 2,
    'icon_hero_id': 100674,
    'label': '蜀.夏侯霸.步',
    'name': '夏侯霸',
    'pinyin': 'xiahouba',
    'quality': 5,
    'season': 'XP',
    'star': 5,
    'value': 100674
  },
  {
    'country': '3',
    'hero_type': 2,
    'icon_hero_id': 100689,
    'label': '蜀.刘禅.步',
    'name': '刘禅',
    'pinyin': 'liuchan',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100689
  },
  {
    'country': '3',
    'hero_type': 2,
    'icon_hero_id': 100691,
    'label': '蜀.周仓.步',
    'name': '周仓',
    'pinyin': 'zhoucang',
    'quality': 5,
    'season': 'XP',
    'star': 5,
    'value': 100691
  },
  {
    'country': '3',
    'hero_type': 2,
    'icon_hero_id': 100698,
    'label': '蜀.简雍.步',
    'name': '简雍',
    'pinyin': 'jianyong',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100698
  },
  {
    'country': '3',
    'hero_type': 1,
    'icon_hero_id': 110311,
    'label': '蜀.侍卫.弓',
    'name': '侍卫',
    'pinyin': 'shiwei',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 110331
  },
  {
    'country': '3',
    'hero_type': 2,
    'icon_hero_id': 110311,
    'label': '蜀.侍卫.步',
    'name': '侍卫',
    'pinyin': 'shiwei',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 110332
  },
  {
    'country': '3',
    'hero_type': 3,
    'icon_hero_id': 110311,
    'label': '蜀.侍卫.骑',
    'name': '侍卫',
    'pinyin': 'shiwei',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 110333
  },
  {
    'country': '3',
    'hero_type': 1,
    'icon_hero_id': 110411,
    'label': '蜀.侍卫.弓',
    'name': '侍卫',
    'pinyin': 'shiwei',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 110431
  },
  {
    'country': '3',
    'hero_type': 2,
    'icon_hero_id': 110411,
    'label': '蜀.侍卫.步',
    'name': '侍卫',
    'pinyin': 'shiwei',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 110432
  },
  {
    'country': '3',
    'hero_type': 3,
    'icon_hero_id': 110411,
    'label': '蜀.侍卫.骑',
    'name': '侍卫',
    'pinyin': 'shiwei',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 110433
  }
]
// 晋
export const heroJin = [
  {
    'country': '6',
    'hero_type': 3,
    'icon_hero_id': 100701,
    'label': '晋.司马师.骑',
    'name': '司马师',
    'pinyin': 'simashi',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100701
  },
  {
    'country': '6',
    'hero_type': 3,
    'icon_hero_id': 100702,
    'label': '晋.司马昭.骑',
    'name': '司马昭',
    'pinyin': 'simazhao',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100702
  },
  {
    'country': '6',
    'hero_type': 2,
    'icon_hero_id': 100703,
    'label': '晋.司马炎.步',
    'name': '司马炎',
    'pinyin': 'simayan',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100703
  },
  {
    'country': '6',
    'hero_type': 3,
    'icon_hero_id': 100704,
    'label': '晋.文鸯.骑',
    'name': '文鸯',
    'pinyin': 'wenyang',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100704
  },
  {
    'country': '6',
    'hero_type': 1,
    'icon_hero_id': 100705,
    'label': '晋.杜预.弓',
    'name': '杜预',
    'pinyin': 'duyu',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100705
  },
  {
    'country': '6',
    'hero_type': 1,
    'icon_hero_id': 100706,
    'label': '晋.王元姬.弓',
    'name': '王元姬',
    'pinyin': 'wangyuanji',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100706
  },
  {
    'country': '6',
    'hero_type': 2,
    'icon_hero_id': 100707,
    'label': '晋.卫瓘.步',
    'name': '卫瓘',
    'pinyin': 'weiguan',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100707
  },
  {
    'country': '6',
    'hero_type': 2,
    'icon_hero_id': 100708,
    'label': '晋.贾充.步',
    'name': '贾充',
    'pinyin': 'jiachong',
    'quality': 5,
    'season': 'XP',
    'star': 5,
    'value': 100708
  },
  {
    'country': '6',
    'hero_type': 2,
    'icon_hero_id': 100709,
    'label': '晋.羊祜.步',
    'name': '羊祜',
    'pinyin': 'yanghu',
    'quality': 5,
    'season': 'XP',
    'star': 5,
    'value': 100709
  },
  {
    'country': '6',
    'hero_type': 2,
    'icon_hero_id': 100711,
    'label': '晋.刘伶.步',
    'name': '刘伶',
    'pinyin': 'liuling',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100711
  },
  {
    'country': '6',
    'hero_type': 1,
    'icon_hero_id': 100713,
    'label': '晋.山涛.弓',
    'name': '山涛',
    'pinyin': 'shantao',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100713
  },
  {
    'country': '6',
    'hero_type': 2,
    'icon_hero_id': 100714,
    'label': '晋.向秀.步',
    'name': '向秀',
    'pinyin': 'xiangxiu',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100714
  },
  {
    'country': '6',
    'hero_type': 2,
    'icon_hero_id': 100715,
    'label': '晋.阮咸.步',
    'name': '阮咸',
    'pinyin': 'ruanxian',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100715
  },
  {
    'country': '6',
    'hero_type': 3,
    'icon_hero_id': 100716,
    'label': '晋.王戎.骑',
    'name': '王戎',
    'pinyin': 'wangrong',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100716
  },
  {
    'country': '6',
    'hero_type': 1,
    'icon_hero_id': 100717,
    'label': '晋.司马攸.弓',
    'name': '司马攸',
    'pinyin': 'simayou',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100717
  },
  {
    'country': '6',
    'hero_type': 1,
    'icon_hero_id': 100718,
    'label': '晋.文虎.弓',
    'name': '文虎',
    'pinyin': 'wenhu',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100718
  },
  {
    'country': '6',
    'hero_type': 1,
    'icon_hero_id': 100591,
    'label': '晋.钟会.SP.弓',
    'name': '钟会',
    'pinyin': 'zhonghui',
    'quality': 5,
    'season': 'SP',
    'star': 5,
    'value': 100731
  },
  {
    'country': '6',
    'hero_type': 1,
    'icon_hero_id': 110311,
    'label': '晋.侍卫.弓',
    'name': '侍卫',
    'pinyin': 'shiwei',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 110361
  },
  {
    'country': '6',
    'hero_type': 2,
    'icon_hero_id': 110311,
    'label': '晋.侍卫.步',
    'name': '侍卫',
    'pinyin': 'shiwei',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 110362
  },
  {
    'country': '6',
    'hero_type': 3,
    'icon_hero_id': 110311,
    'label': '晋.侍卫.骑',
    'name': '侍卫',
    'pinyin': 'shiwei',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 110363
  },
  {
    'country': '6',
    'hero_type': 1,
    'icon_hero_id': 110411,
    'label': '晋.侍卫.弓',
    'name': '侍卫',
    'pinyin': 'shiwei',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 110461
  },
  {
    'country': '6',
    'hero_type': 2,
    'icon_hero_id': 110411,
    'label': '晋.侍卫.步',
    'name': '侍卫',
    'pinyin': 'shiwei',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 110462
  },
  {
    'country': '6',
    'hero_type': 3,
    'icon_hero_id': 110411,
    'label': '晋.侍卫.骑',
    'name': '侍卫',
    'pinyin': 'shiwei',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 110463
  }
]
// 魏
export const heroWei = [
  {
    'country': '2',
    'hero_type': 3,
    'icon_hero_id': 100023,
    'label': '魏.曹操.骑',
    'name': '曹操',
    'pinyin': 'caocao',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100023
  },
  {
    'country': '2',
    'hero_type': 3,
    'icon_hero_id': 100024,
    'label': '魏.荀彧.骑',
    'name': '荀彧',
    'pinyin': 'xunyu',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100024
  },
  {
    'country': '2',
    'hero_type': 1,
    'icon_hero_id': 100025,
    'label': '魏.曹丕.弓',
    'name': '曹丕',
    'pinyin': 'caopi',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100025
  },
  {
    'country': '2',
    'hero_type': 1,
    'icon_hero_id': 100029,
    'label': '魏.张春华.弓',
    'name': '张春华',
    'pinyin': 'zhangchunhua',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100029
  },
  {
    'country': '2',
    'hero_type': 3,
    'icon_hero_id': 100026,
    'label': '魏.关羽.骑',
    'name': '关羽',
    'pinyin': 'guanyu',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100026
  },
  {
    'country': '2',
    'hero_type': 3,
    'icon_hero_id': 100027,
    'label': '魏.张辽.骑',
    'name': '张辽',
    'pinyin': 'zhangliao',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100027
  },
  {
    'country': '2',
    'hero_type': 1,
    'icon_hero_id': 100028,
    'label': '魏.王异.弓',
    'name': '王异',
    'pinyin': 'wangyi',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100028
  },
  {
    'country': '2',
    'hero_type': 1,
    'icon_hero_id': 100075,
    'label': '魏.郭皇后.弓',
    'name': '郭皇后',
    'pinyin': 'guohuanghou',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100075
  },
  {
    'country': '2',
    'hero_type': 3,
    'icon_hero_id': 100076,
    'label': '魏.卞夫人.骑',
    'name': '卞夫人',
    'pinyin': 'panfuren',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100076
  },
  {
    'country': '2',
    'hero_type': 2,
    'icon_hero_id': 100077,
    'label': '魏.丁夫人.步',
    'name': '丁夫人',
    'pinyin': 'dingfuren',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100077
  },
  {
    'country': '2',
    'hero_type': 3,
    'icon_hero_id': 100078,
    'label': '魏.郭嘉.骑',
    'name': '郭嘉',
    'pinyin': 'guojia',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100078
  },
  {
    'country': '2',
    'hero_type': 3,
    'icon_hero_id': 100079,
    'label': '魏.夏侯惇.骑',
    'name': '夏侯惇',
    'pinyin': 'xiahoudun',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100079
  },
  {
    'country': '2',
    'hero_type': 2,
    'icon_hero_id': 100081,
    'label': '魏.典韦.步',
    'name': '典韦',
    'pinyin': 'dianwei',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100081
  },
  {
    'country': '2',
    'hero_type': 3,
    'icon_hero_id': 100085,
    'label': '魏.曹仁.骑',
    'name': '曹仁',
    'pinyin': 'caoren',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100085
  },
  {
    'country': '2',
    'hero_type': 1,
    'icon_hero_id': 100145,
    'label': '魏.夏侯渊.弓',
    'name': '夏侯渊',
    'pinyin': 'xiahouyuan',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100145
  },
  {
    'country': '2',
    'hero_type': 3,
    'icon_hero_id': 100148,
    'label': '魏.曹彰.骑',
    'name': '曹彰',
    'pinyin': 'caozhang',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100148
  },
  {
    'country': '2',
    'hero_type': 2,
    'icon_hero_id': 100149,
    'label': '魏.程昱.步',
    'name': '程昱',
    'pinyin': 'chengyu',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100149
  },
  {
    'country': '2',
    'hero_type': 2,
    'icon_hero_id': 100150,
    'label': '魏.荀攸.步',
    'name': '荀攸',
    'pinyin': 'xunyou',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100150
  },
  {
    'country': '2',
    'hero_type': 3,
    'icon_hero_id': 100421,
    'label': '魏.徐晃.骑',
    'name': '徐晃',
    'pinyin': 'xuhuang',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100421
  },
  {
    'country': '2',
    'hero_type': 2,
    'icon_hero_id': 100083,
    'label': '魏.张郃.步',
    'name': '张郃',
    'pinyin': 'zhangxia',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100083
  },
  {
    'country': '2',
    'hero_type': 3,
    'icon_hero_id': 100084,
    'label': '魏.庞德.骑',
    'name': '庞德',
    'pinyin': 'pangde',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100084
  },
  {
    'country': '2',
    'hero_type': 2,
    'icon_hero_id': 100310,
    'label': '魏.邓艾.步',
    'name': '邓艾',
    'pinyin': 'dengai',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100310
  },
  {
    'country': '2',
    'hero_type': 2,
    'icon_hero_id': 100472,
    'label': '魏.司马懿.步',
    'name': '司马懿',
    'pinyin': 'simayi',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100472
  },
  {
    'country': '2',
    'hero_type': 3,
    'icon_hero_id': 100420,
    'label': '魏.夏侯渊.骑',
    'name': '夏侯渊',
    'pinyin': 'xiahouyuan',
    'quality': 4,
    'season': 'S2',
    'star': 4,
    'value': 100420
  },
  {
    'country': '2',
    'hero_type': 3,
    'icon_hero_id': 100435,
    'label': '魏.夏侯渊.骑',
    'name': '夏侯渊',
    'pinyin': 'xiahouyuan',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100435
  },
  {
    'country': '2',
    'hero_type': 2,
    'icon_hero_id': 100475,
    'label': '魏.郝昭.步',
    'name': '郝昭',
    'pinyin': 'haozhao',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100475
  },
  {
    'country': '2',
    'hero_type': 3,
    'icon_hero_id': 100476,
    'label': '魏.郭嘉.骑',
    'name': '郭嘉',
    'pinyin': 'guojia',
    'quality': 5,
    'season': 'S2',
    'star': 5,
    'value': 100476
  },
  {
    'country': '2',
    'hero_type': 3,
    'icon_hero_id': 100521,
    'label': '魏.文聘.骑',
    'name': '文聘',
    'pinyin': 'wenpin',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100521
  },
  {
    'country': '2',
    'hero_type': 2,
    'icon_hero_id': 100583,
    'label': '魏.荀攸.SP.步',
    'name': '荀攸',
    'pinyin': 'xunyou',
    'quality': 5,
    'season': 'SP',
    'star': 5,
    'value': 100583
  },
  {
    'country': '2',
    'hero_type': 1,
    'icon_hero_id': 100591,
    'label': '魏.钟会.弓',
    'name': '钟会',
    'pinyin': 'zhonghui',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100591
  },
  {
    'country': '2',
    'hero_type': 3,
    'icon_hero_id': 100603,
    'label': '魏.卞夫人.骑',
    'name': '卞夫人',
    'pinyin': 'panfuren',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100603
  },
  {
    'country': '2',
    'hero_type': 3,
    'icon_hero_id': 100435,
    'label': '魏.夏侯渊.SP.骑',
    'name': '夏侯渊',
    'pinyin': 'xiahouyuan',
    'quality': 5,
    'season': 'SP',
    'star': 5,
    'value': 102002
  },
  {
    'country': '2',
    'hero_type': 3,
    'icon_hero_id': 100498,
    'label': '魏.曹纯.骑',
    'name': '曹纯',
    'pinyin': 'caochun',
    'quality': 5,
    'season': 'S3',
    'star': 5,
    'value': 100498
  },
  {
    'country': '2',
    'hero_type': 1,
    'icon_hero_id': 100502,
    'label': '魏.曹植.弓',
    'name': '曹植',
    'pinyin': 'caozhi',
    'quality': 4,
    'season': 'S3',
    'star': 4,
    'value': 100502
  },
  {
    'country': '2',
    'hero_type': 2,
    'icon_hero_id': 100503,
    'label': '魏.戏志才.步',
    'name': '戏志才',
    'pinyin': 'xizhicai',
    'quality': 4,
    'season': 'S3',
    'star': 4,
    'value': 100503
  },
  {
    'country': '2',
    'hero_type': 3,
    'icon_hero_id': 100083,
    'label': '魏.张郃.SP.骑',
    'name': '张郃',
    'pinyin': 'zhangxia',
    'quality': 5,
    'season': 'SP',
    'star': 5,
    'value': 102013
  },
  {
    'country': '2',
    'hero_type': 3,
    'icon_hero_id': 100449,
    'label': '魏.夏侯惇.骑',
    'name': '夏侯惇',
    'pinyin': 'xiahoudun',
    'quality': 5,
    'season': 'XP',
    'star': 5,
    'value': 100449
  },
  {
    'country': '2',
    'hero_type': 3,
    'icon_hero_id': 100143,
    'label': '魏.于禁.骑',
    'name': '于禁',
    'pinyin': 'yujin',
    'quality': 4,
    'season': 'XP',
    'star': 4,
    'value': 100531
  },
  {
    'country': '2',
    'hero_type': 2,
    'icon_hero_id': 100314,
    'label': '魏.辛宪英.步',
    'name': '辛宪英',
    'pinyin': 'xinxianying',
    'quality': 4,
    'season': 'XP',
    'star': 4,
    'value': 100314
  },
  {
    'country': '2',
    'hero_type': 2,
    'icon_hero_id': 100585,
    'label': '魏.曹仁.SP.步',
    'name': '曹仁',
    'pinyin': 'caoren',
    'quality': 5,
    'season': 'SP',
    'star': 5,
    'value': 100585
  },
  {
    'country': '2',
    'hero_type': 1,
    'icon_hero_id': 100618,
    'label': '魏.贾诩.弓',
    'name': '贾诩',
    'pinyin': 'jiaxu',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100618
  },
  {
    'country': '2',
    'hero_type': 3,
    'icon_hero_id': 100643,
    'label': '魏.文钦.骑',
    'name': '文钦',
    'pinyin': 'wenqin',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100643
  },
  {
    'country': '2',
    'hero_type': 2,
    'icon_hero_id': 100644,
    'label': '魏.王双.步',
    'name': '王双',
    'pinyin': 'wangshuang',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100644
  },
  {
    'country': '2',
    'hero_type': 3,
    'icon_hero_id': 100645,
    'label': '魏.徐晃.骑',
    'name': '徐晃',
    'pinyin': 'xuhuang',
    'quality': 5,
    'season': 'XP',
    'star': 5,
    'value': 100645
  },
  {
    'country': '2',
    'hero_type': 1,
    'icon_hero_id': 100652,
    'label': '魏.王朗.弓',
    'name': '王朗',
    'pinyin': 'wanglang',
    'quality': 5,
    'season': 'XP',
    'star': 5,
    'value': 100652
  },
  {
    'country': '2',
    'hero_type': 1,
    'icon_hero_id': 100655,
    'label': '魏.郭皇后.弓',
    'name': '郭皇后',
    'pinyin': 'guohuanghou',
    'quality': 5,
    'season': 'XP',
    'star': 5,
    'value': 100655
  },
  {
    'country': '2',
    'hero_type': 3,
    'icon_hero_id': 100672,
    'label': '魏.曹植.骑',
    'name': '曹植',
    'pinyin': 'caozhi',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100672
  },
  {
    'country': '2',
    'hero_type': 3,
    'icon_hero_id': 100683,
    'label': '魏.曹彰.骑',
    'name': '曹彰',
    'pinyin': 'caozhang',
    'quality': 5,
    'season': 'XP',
    'star': 5,
    'value': 100683
  },
  {
    'country': '2',
    'hero_type': 2,
    'icon_hero_id': 100685,
    'label': '魏.乐进.步',
    'name': '乐进',
    'pinyin': 'yuejin',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100685
  },
  {
    'country': '2',
    'hero_type': 1,
    'icon_hero_id': 100699,
    'label': '魏.华歆.弓',
    'name': '华歆',
    'pinyin': 'huaxin',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100699
  },
  {
    'country': '2',
    'hero_type': 2,
    'icon_hero_id': 100710,
    'label': '魏.嵇康.步',
    'name': '嵇康',
    'pinyin': 'jikang',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100710
  },
  {
    'country': '2',
    'hero_type': 2,
    'icon_hero_id': 100712,
    'label': '魏.阮籍.步',
    'name': '阮籍',
    'pinyin': 'ruanji',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100712
  },
  {
    'country': '2',
    'hero_type': 2,
    'icon_hero_id': 100769,
    'label': '魏.典韦.步',
    'name': '典韦',
    'pinyin': 'dianwei',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100769
  },
  {
    'country': '2',
    'hero_type': 3,
    'icon_hero_id': 100719,
    'label': '魏.曹爽.骑',
    'name': '曹爽',
    'pinyin': 'caoshuang',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100719
  },
  {
    'country': '2',
    'hero_type': 1,
    'icon_hero_id': 110311,
    'label': '魏.侍卫.弓',
    'name': '侍卫',
    'pinyin': 'shiwei',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 110321
  },
  {
    'country': '2',
    'hero_type': 2,
    'icon_hero_id': 110311,
    'label': '魏.侍卫.步',
    'name': '侍卫',
    'pinyin': 'shiwei',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 110322
  },
  {
    'country': '2',
    'hero_type': 3,
    'icon_hero_id': 110311,
    'label': '魏.侍卫.骑',
    'name': '侍卫',
    'pinyin': 'shiwei',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 110323
  },
  {
    'country': '2',
    'hero_type': 1,
    'icon_hero_id': 110411,
    'label': '魏.侍卫.弓',
    'name': '侍卫',
    'pinyin': 'shiwei',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 110421
  },
  {
    'country': '2',
    'hero_type': 2,
    'icon_hero_id': 110411,
    'label': '魏.侍卫.步',
    'name': '侍卫',
    'pinyin': 'shiwei',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 110422
  },
  {
    'country': '2',
    'hero_type': 3,
    'icon_hero_id': 110411,
    'label': '魏.侍卫.骑',
    'name': '侍卫',
    'pinyin': 'shiwei',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 110423
  }
]
// 汉
export const heroHan = [
  {
    'country': '1',
    'hero_type': 3,
    'icon_hero_id': 100003,
    'label': '汉.吕布.骑',
    'name': '吕布',
    'pinyin': 'lvbu',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100003
  },
  {
    'country': '1',
    'hero_type': 1,
    'icon_hero_id': 100005,
    'label': '汉.貂蝉.弓',
    'name': '貂蝉',
    'pinyin': 'diaochan',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100005
  },
  {
    'country': '1',
    'hero_type': 2,
    'icon_hero_id': 100006,
    'label': '汉.袁绍.步',
    'name': '袁绍',
    'pinyin': 'yuanshao',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100006
  },
  {
    'country': '1',
    'hero_type': 3,
    'icon_hero_id': 100007,
    'label': '汉.卢植.骑',
    'name': '卢植',
    'pinyin': 'luzhi',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100007
  },
  {
    'country': '1',
    'hero_type': 1,
    'icon_hero_id': 100037,
    'label': '汉.何太后.弓',
    'name': '何太后',
    'pinyin': 'hetaihou',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100037
  },
  {
    'country': '1',
    'hero_type': 1,
    'icon_hero_id': 100101,
    'label': '汉.灵帝.弓',
    'name': '灵帝',
    'pinyin': 'lingdi',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100101
  },
  {
    'country': '1',
    'hero_type': 3,
    'icon_hero_id': 100004,
    'label': '汉.蔡文姬.骑',
    'name': '蔡文姬',
    'pinyin': 'caiwenji',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100004
  },
  {
    'country': '1',
    'hero_type': 1,
    'icon_hero_id': 100002,
    'label': '汉.十常侍.弓',
    'name': '十常侍',
    'pinyin': 'shichangshi',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100002
  },
  {
    'country': '1',
    'hero_type': 1,
    'icon_hero_id': 100001,
    'label': '汉.献帝.弓',
    'name': '献帝',
    'pinyin': 'xiandi',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100001
  },
  {
    'country': '1',
    'hero_type': 3,
    'icon_hero_id': 100038,
    'label': '汉.王美人.骑',
    'name': '王美人',
    'pinyin': 'wangmeiren',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100038
  },
  {
    'country': '1',
    'hero_type': 3,
    'icon_hero_id': 100039,
    'label': '汉.皇甫嵩.骑',
    'name': '皇甫嵩',
    'pinyin': 'huangfusong',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100039
  },
  {
    'country': '1',
    'hero_type': 1,
    'icon_hero_id': 100040,
    'label': '汉.朱儁.弓',
    'name': '朱儁',
    'pinyin': 'zhujun',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100040
  },
  {
    'country': '1',
    'hero_type': 2,
    'icon_hero_id': 100041,
    'label': '汉.张奂.步',
    'name': '张奂',
    'pinyin': 'zhanghuan',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100041
  },
  {
    'country': '1',
    'hero_type': 3,
    'icon_hero_id': 100042,
    'label': '汉.曹操.骑',
    'name': '曹操',
    'pinyin': 'caocao',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100042
  },
  {
    'country': '1',
    'hero_type': 3,
    'icon_hero_id': 100043,
    'label': '汉.孙坚.骑',
    'name': '孙坚',
    'pinyin': 'sunjian',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100043
  },
  {
    'country': '1',
    'hero_type': 2,
    'icon_hero_id': 100044,
    'label': '汉.刘备.步',
    'name': '刘备',
    'pinyin': 'liubei',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100044
  },
  {
    'country': '1',
    'hero_type': 1,
    'icon_hero_id': 100378,
    'label': '汉.伏寿.弓',
    'name': '伏寿',
    'pinyin': 'fushou',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100378
  },
  {
    'country': '1',
    'hero_type': 2,
    'icon_hero_id': 100379,
    'label': '汉.杜氏.步',
    'name': '杜氏',
    'pinyin': 'dushi',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100379
  },
  {
    'country': '1',
    'hero_type': 3,
    'icon_hero_id': 100471,
    'label': '汉.曹节.骑',
    'name': '曹节',
    'pinyin': 'caojie',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100471
  },
  {
    'country': '1',
    'hero_type': 2,
    'icon_hero_id': 100354,
    'label': '汉.司马徽.步',
    'name': '司马徽',
    'pinyin': 'simahui',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100354
  },
  {
    'country': '1',
    'hero_type': 2,
    'icon_hero_id': 100355,
    'label': '汉.蔡夫人.步',
    'name': '蔡夫人',
    'pinyin': 'caifuren',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100355
  },
  {
    'country': '1',
    'hero_type': 1,
    'icon_hero_id': 100045,
    'label': '汉.鲍信.弓',
    'name': '鲍信',
    'pinyin': 'baoxin',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100045
  },
  {
    'country': '1',
    'hero_type': 2,
    'icon_hero_id': 100480,
    'label': '汉.董卓.步',
    'name': '董卓',
    'pinyin': 'dongzhuo',
    'quality': 5,
    'season': 'S2',
    'star': 5,
    'value': 100480
  },
  {
    'country': '1',
    'hero_type': 3,
    'icon_hero_id': 100114,
    'label': '汉.公孙瓒.骑',
    'name': '公孙瓒',
    'pinyin': 'gongsunzan',
    'quality': 4,
    'season': 'S2',
    'star': 4,
    'value': 100484
  },
  {
    'country': '1',
    'hero_type': 3,
    'icon_hero_id': 100486,
    'label': '汉.潘凤.骑',
    'name': '潘凤',
    'pinyin': 'panfeng',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100486
  },
  {
    'country': '1',
    'hero_type': 2,
    'icon_hero_id': 100369,
    'label': '汉.华佗.步',
    'name': '华佗',
    'pinyin': 'huatuo',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100369
  },
  {
    'country': '1',
    'hero_type': 3,
    'icon_hero_id': 100007,
    'label': '汉.卢植.SP.骑',
    'name': '卢植',
    'pinyin': 'luzhi',
    'quality': 5,
    'season': 'SP',
    'star': 5,
    'value': 102004
  },
  {
    'country': '1',
    'hero_type': 2,
    'icon_hero_id': 100041,
    'label': '汉.张奂.SP.步',
    'name': '张奂',
    'pinyin': 'zhanghuan',
    'quality': 4,
    'season': 'SP',
    'star': 4,
    'value': 102009
  },
  {
    'country': '1',
    'hero_type': 2,
    'icon_hero_id': 100004,
    'label': '汉.蔡文姬.SP.步',
    'name': '蔡文姬',
    'pinyin': 'caiwenji',
    'quality': 5,
    'season': 'SP',
    'star': 5,
    'value': 102011
  },
  {
    'country': '1',
    'hero_type': 1,
    'icon_hero_id': 100526,
    'label': '汉.张机.弓',
    'name': '张机',
    'pinyin': 'zhangji',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100526
  },
  {
    'country': '1',
    'hero_type': 1,
    'icon_hero_id': 100107,
    'label': '汉.刘表.弓',
    'name': '刘表',
    'pinyin': 'liubiao',
    'quality': 4,
    'season': 'XP',
    'star': 4,
    'value': 100530
  },
  {
    'country': '1',
    'hero_type': 1,
    'icon_hero_id': 100359,
    'label': '汉.袁姬.弓',
    'name': '袁姬',
    'pinyin': 'yuanji',
    'quality': 4,
    'season': 'XP',
    'star': 4,
    'value': 100359
  },
  {
    'country': '1',
    'hero_type': 1,
    'icon_hero_id': 100553,
    'label': '汉.朱儁.SP.弓',
    'name': '朱儁',
    'pinyin': 'zhujun',
    'quality': 5,
    'season': 'SP',
    'star': 5,
    'value': 100553
  },
  {
    'country': '1',
    'hero_type': 3,
    'icon_hero_id': 100098,
    'label': '汉.何进.骑',
    'name': '何进',
    'pinyin': 'hejin',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100570
  },
  {
    'country': '1',
    'hero_type': 2,
    'icon_hero_id': 100630,
    'label': '汉.皇甫嵩.步',
    'name': '皇甫嵩',
    'pinyin': 'huangfusong',
    'quality': 5,
    'season': 'XP',
    'star': 5,
    'value': 100630
  },
  {
    'country': '1',
    'hero_type': 3,
    'icon_hero_id': 100100,
    'label': '汉.董承.骑',
    'name': '董承',
    'pinyin': 'dongcheng',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100669
  },
  {
    'country': '1',
    'hero_type': 1,
    'icon_hero_id': 100675,
    'label': '汉.刘表.弓',
    'name': '刘表',
    'pinyin': 'liubiao',
    'quality': 5,
    'season': 'XP',
    'star': 5,
    'value': 100675
  },
  {
    'country': '1',
    'hero_type': 3,
    'icon_hero_id': 100676,
    'label': '汉.王昭君.骑',
    'name': '王昭君',
    'pinyin': 'wangzhaojun',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100676
  },
  {
    'country': '1',
    'hero_type': 1,
    'icon_hero_id': 100693,
    'label': '汉.王允.弓',
    'name': '王允',
    'pinyin': 'wangyun',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100693
  },
  {
    'country': '1',
    'hero_type': 3,
    'icon_hero_id': 100694,
    'label': '汉.张邈.骑',
    'name': '张邈',
    'pinyin': 'zhangmiao',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100694
  },
  {
    'country': '1',
    'hero_type': 3,
    'icon_hero_id': 100695,
    'label': '汉.刘岱.骑',
    'name': '刘岱',
    'pinyin': 'liudai',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100695
  },
  {
    'country': '1',
    'hero_type': 1,
    'icon_hero_id': 100696,
    'label': '汉.孔融.弓',
    'name': '孔融',
    'pinyin': 'kongrong',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100696
  },
  {
    'country': '1',
    'hero_type': 1,
    'icon_hero_id': 100697,
    'label': '汉.陶谦.弓',
    'name': '陶谦',
    'pinyin': 'taoqian',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 100697
  },
  {
    'country': '1',
    'hero_type': 1,
    'icon_hero_id': 100742,
    'label': '汉.阴丽华.弓',
    'name': '阴丽华',
    'pinyin': 'yinlihua',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100742
  },
  {
    'country': '1',
    'hero_type': 1,
    'icon_hero_id': 100770,
    'label': '汉.许劭.弓',
    'name': '许劭',
    'pinyin': 'xushao',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 100770
  },
  {
    'country': '1',
    'hero_type': 1,
    'icon_hero_id': 110311,
    'label': '汉.侍卫.弓',
    'name': '侍卫',
    'pinyin': 'shiwei',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 110311
  },
  {
    'country': '1',
    'hero_type': 2,
    'icon_hero_id': 110311,
    'label': '汉.侍卫.步',
    'name': '侍卫',
    'pinyin': 'shiwei',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 110312
  },
  {
    'country': '1',
    'hero_type': 3,
    'icon_hero_id': 110311,
    'label': '汉.侍卫.骑',
    'name': '侍卫',
    'pinyin': 'shiwei',
    'quality': 4,
    'season': 'N',
    'star': 4,
    'value': 110313
  },
  {
    'country': '1',
    'hero_type': 1,
    'icon_hero_id': 110411,
    'label': '汉.侍卫.弓',
    'name': '侍卫',
    'pinyin': 'shiwei',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 110411
  },
  {
    'country': '1',
    'hero_type': 2,
    'icon_hero_id': 110411,
    'label': '汉.侍卫.步',
    'name': '侍卫',
    'pinyin': 'shiwei',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 110412
  },
  {
    'country': '1',
    'hero_type': 3,
    'icon_hero_id': 110411,
    'label': '汉.侍卫.骑',
    'name': '侍卫',
    'pinyin': 'shiwei',
    'quality': 5,
    'season': 'N',
    'star': 5,
    'value': 110413
  }
]

// 英雄value、name键值对
// @ts-ignore
export const heroMap = [...heroQun, ...heroWu, ...heroShu, ...heroJin, ...heroWei, ...heroHan].reduce((obj:any, item:any) => {
  obj[item.value] = item.label
  return obj
}, {})